title: <p align="center"> Saumya Priyam </p>
logo: /assets/img/priyam.jpg

description:
  <p align="center">
  <a href="priyam_cv.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/saumyapriyam/">LinkedIn</a> |
  <a href="https://github.com/saumyapriyam">GitHub</a>
  
  <br>   
  I'm currently working as a Software Developer at Robert Bosch Engineering India.
  I am working as a Perception Developer for Bosch Radars, for detecting Radar Blindness.
  <br>
  </p>



theme: jekyll-theme-minimal
